import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widget from '../components/Widget'

export default function Home({newsResults,randomUser}) {
  return (
    <div >
      <Head>
        <title>twiter clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className="flex min-h-screen  mx-auto ">

          {/* side bar */}
            <Sidebar />

            {/* feed */}
            <Feed />

            {/* widgets */}
            <Widget 
            newsResults={newsResults.articles}
             randomUser={randomUser.results} />
      </main>
    </div>
  )
}


// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
export async function getServerSideProps(){
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/health/in.json"
  ).then((res) => res.json());
  //followf section
  const randomUser = await fetch(
    "https://randomuser.me/api/?results=50&inc=name,login,picture"
    ).then((res) => res.json());
  return {
    props:{
      newsResults,
      randomUser
    }
  }
}